# Generated by Django 5.2.14 on 2026-06-01 08:13

import api.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('Natural Hazards', 'Natural Hazards'), ('Technological/Industrial Hazards', 'Technological Industral Hazards'), ('Human-Made Crisis', 'Humanmade Crisis')], max_length=255, null=True)),
                ('incident_datetime', models.DateTimeField(blank=True, help_text='Date and time when the incident occurred. If unknown, this can be left blank.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Crises',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infrastructure_latitude', models.FloatField(blank=True, null=True)),
                ('infrastructure_longitude', models.FloatField(blank=True, null=True)),
                ('infrastructure_location_description', models.CharField(blank=True, help_text='Free text description of the infrastructure location', max_length=255, null=True)),
                ('infrastructure_location_name', models.CharField(blank=True, help_text="Name of the infrastructure location (e.g., 'Main Street Bridge', 'Downtown Intersection', etc.)", max_length=255, null=True)),
                ('submit_location_latitude', models.FloatField(blank=True, null=True)),
                ('submit_location_longitude', models.FloatField(blank=True, null=True)),
                ('submit_location_description', models.CharField(blank=True, help_text='Free text description of the submit location', max_length=255, null=True)),
                ('submit_location_name', models.CharField(blank=True, help_text="Name of the submit location (e.g., 'Main Street Bridge', 'Downtown Intersection', etc.)", max_length=255, null=True)),
                ('submit_location_to_infrastructure_distance', models.FloatField(blank=True, help_text='Distance in meters from the submit location to the infrastructure location.', null=True)),
                ('submit_location_to_infrastructure_direction_degrees', models.FloatField(blank=True, help_text='Direction from the submit location to the infrastructure location in degrees (0-360, where 0/360 is north, 90 is east, 180 is south, and 270 is west).', null=True)),
                ('submit_location_to_infrastructure_direction_cardinal', models.CharField(blank=True, choices=[('N', 'N'), ('NE', 'Ne'), ('E', 'E'), ('SE', 'Se'), ('S', 'S'), ('SW', 'Sw'), ('W', 'W'), ('NW', 'Nw')], help_text="Cardinal direction from the submit location to the infrastructure location (e.g., 'N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW').", max_length=255, null=True)),
                ('submit_location_to_infrastructure_direction_description', models.CharField(blank=True, help_text='Free text description of the direction from the submit location to the infrastructure location', max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('state_province', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NatureOfCrisisQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('choice_options', models.JSONField(blank=True, help_text="A JSON array of multiple choice options for the question, if applicable. For example: ['Option 1', 'Option 2', 'Option 3']. If the question is not multiple choice, this can be left blank.", null=True)),
                ('is_multiple_choice', models.BooleanField(default=False, help_text='Indicates whether the question is a multiple choice question or not.')),
                ('nature_of_crisis', models.CharField(blank=True, help_text='The nature of the crisis (e.g., earthquake, flood, hurricane, etc.) that the question is related to.', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=api.models.get_timestamp_path)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrisisQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('choice_options', models.JSONField(blank=True, help_text="A JSON array of multiple choice options for the question, if applicable. For example: ['Option 1', 'Option 2', 'Option 3']. If the question is not multiple choice, this can be left blank.", null=True)),
                ('is_multiple_choice', models.BooleanField(default=False, help_text='Indicates whether the question is a multiple choice question or not.')),
                ('crisis', models.ForeignKey(blank=True, help_text='The crisis event that this question is related to. This can be left blank if the question is not linked to a specific crisis event.', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.crisis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrisisQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, help_text="The answer provided for the question in relation to the specific impact report. For multiple choice questions, this should be one of the options provided in the Question's choice_options field.", max_length=255, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crisisquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('infrastructure_name', models.CharField(blank=True, max_length=255, null=True)),
                ('infrastructure_type', models.CharField(blank=True, help_text='e.g., bridge, road, building, etc.', max_length=255, null=True)),
                ('infrastructure_description', models.TextField(blank=True, max_length=255, null=True)),
                ('damage_severity', models.CharField(blank=True, choices=[('No Damage', 'No Damage'), ('Minimal', 'Minimal'), ('Partial', 'Partial'), ('Complete', 'Complete')], max_length=255, null=True)),
                ('nature_of_crisis', models.CharField(blank=True, help_text='e.g., earthquake, flood, hurricane, etc.', max_length=255, null=True)),
                ('nature_of_crisis_category', models.CharField(blank=True, choices=[('Natural Hazards', 'Natural Hazards'), ('Technological/Industrial Hazards', 'Technological Industral Hazards'), ('Human-Made Crisis', 'Humanmade Crisis')], help_text='e.g., natural disaster, human-made crisis, etc.', max_length=255, null=True)),
                ('debris', models.BooleanField(default=False, help_text='Indicates if there is debris present at the site.')),
                ('debris_description', models.TextField(blank=True, help_text='Description of the debris, if present.', max_length=255, null=True)),
                ('accessibility', models.BooleanField(default=True, help_text='Indicates if the infrastructure is accessible or not.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('damage_datetime', models.DateTimeField(blank=True, help_text='Date and time when the incident occurred. If unknown, this can be left blank.', null=True)),
                ('crisis', models.ForeignKey(blank=True, help_text='The crisis event that this impact report is related to. This can be left blank if the report is not linked to a specific crisis event.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.crisis')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location')),
                ('photos', models.ManyToManyField(to='api.photo')),
            ],
        ),
        migrations.CreateModel(
            name='NatureOfCrisisQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, help_text="The answer provided for the question in relation to the specific impact report. For multiple choice questions, this should be one of the options provided in the Question's choice_options field.", max_length=255, null=True)),
                ('impact_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.impactreport')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.natureofcrisisquestion')),
            ],
        ),
    ]
