# Generated by Django 5.2.14 on 2026-06-18 02:07

import api.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('infrastructure_latitude', models.FloatField(blank=True, null=True)),
                ('infrastructure_longitude', models.FloatField(blank=True, null=True)),
                ('infrastructure_location_description', models.CharField(blank=True, help_text='Free text description of the infrastructure location', max_length=255, null=True)),
                ('infrastructure_location_name', models.CharField(blank=True, help_text="Name of the infrastructure location (e.g., 'Main Street Bridge', 'Downtown Intersection', etc.)", max_length=255, null=True)),
                ('submit_location_latitude', models.FloatField(blank=True, null=True)),
                ('submit_location_longitude', models.FloatField(blank=True, null=True)),
                ('submit_location_description', models.CharField(blank=True, help_text='Free text description of the submit location', max_length=255, null=True)),
                ('submit_location_name', models.CharField(blank=True, help_text="Name of the submit location (e.g., 'Main Street Bridge', 'Downtown Intersection', etc.)", max_length=255, null=True)),
                ('submit_location_to_infrastructure_distance', models.FloatField(blank=True, help_text='Distance in meters from the submit location to the infrastructure location.', null=True)),
                ('submit_location_to_infrastructure_direction_degrees', models.FloatField(blank=True, help_text='Direction from the submit location to the infrastructure location in degrees (0-360, where 0/360 is north, 90 is east, 180 is south, and 270 is west).', null=True)),
                ('submit_location_to_infrastructure_direction_cardinal', models.CharField(blank=True, choices=[('N', 'N'), ('NE', 'Ne'), ('E', 'E'), ('SE', 'Se'), ('S', 'S'), ('SW', 'Sw'), ('W', 'W'), ('NW', 'Nw')], help_text="Cardinal direction from the submit location to the infrastructure location (e.g., 'N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW').", max_length=255, null=True)),
                ('submit_location_to_infrastructure_direction_description', models.CharField(blank=True, help_text='Free text description of the direction from the submit location to the infrastructure location', max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('state_province', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, help_text='Free text description of the location', max_length=255, null=True)),
                ('name', models.CharField(blank=True, help_text="Name of the location (e.g., 'Main Street Bridge', 'Downtown Intersection', etc.)", max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('state_province', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to=api.models.get_timestamp_path)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('exif_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('choice_options', models.JSONField(blank=True, help_text="A JSON array of multiple choice options for the question, if applicable. For example: ['Option 1', 'Option 2', 'Option 3']. If the question is not multiple choice, this can be left blank.", null=True)),
                ('is_multiple_choice', models.BooleanField(default=False, help_text='Indicates whether the question is a multiple choice question or not.')),
            ],
        ),
        migrations.CreateModel(
            name='CIRUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('job_title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('pseudonym', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.location')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ImpactReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('infrastructure_name', models.CharField(blank=True, max_length=255, null=True)),
                ('infrastructure_type', models.CharField(blank=True, help_text='e.g., bridge, road, building, etc.', max_length=255, null=True)),
                ('infrastructure_description', models.TextField(blank=True, max_length=255, null=True)),
                ('damage_severity', models.CharField(blank=True, choices=[('No Damage', 'No Damage'), ('Minimal', 'Minimal'), ('Partial', 'Partial'), ('Complete', 'Complete')], max_length=255, null=True)),
                ('debris', models.BooleanField(default=False, help_text='Indicates if there is debris present at the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('damage_datetime', models.DateTimeField(blank=True, help_text='Date and time when the incident occurred. If unknown, this can be left blank.', null=True)),
                ('electricity_condition', models.CharField(choices=[('no_damage', 'No Damage'), ('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('destroyed', 'Destroyed'), ('unknown', 'Unknown')], default='no_damage', max_length=20)),
                ('health_services_rating', models.CharField(choices=[('fully', 'Fully'), ('partial', 'Partial'), ('largely_disrupted', 'Largly Disrupted'), ('not_functioning', 'Not Functioning'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('pressing_need', models.TextField(default='')),
                ('annotations', models.JSONField(blank=True, help_text='GeoJSON annotation data drawn on the map by the reporter (polygon, radius, point, direction, position).', null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.infrastructurelocation')),
                ('photos', models.ManyToManyField(to='api.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, help_text="The answer provided for the question in relation to the specific impact report. For multiple choice questions, this should be one of the options provided in the Question's choice_options field.", max_length=255, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question2')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance_threshold_in_km', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('impact_report', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.impactreport')),
            ],
        ),
        migrations.AddField(
            model_name='question2',
            name='question_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.questiongroup'),
        ),
    ]
