# Generated by Django 5.2.14 on 2026-06-15 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infrastructure_latitude', models.FloatField(blank=True, null=True)),
                ('infrastructure_longitude', models.FloatField(blank=True, null=True)),
                ('infrastructure_location_description', models.CharField(blank=True, help_text='Free text description of the infrastructure location', max_length=255, null=True)),
                ('infrastructure_location_name', models.CharField(blank=True, help_text="Name of the infrastructure location (e.g., 'Main Street Bridge', 'Downtown Intersection', etc.)", max_length=255, null=True)),
                ('submit_location_latitude', models.FloatField(blank=True, null=True)),
                ('submit_location_longitude', models.FloatField(blank=True, null=True)),
                ('submit_location_description', models.CharField(blank=True, help_text='Free text description of the submit location', max_length=255, null=True)),
                ('submit_location_name', models.CharField(blank=True, help_text="Name of the submit location (e.g., 'Main Street Bridge', 'Downtown Intersection', etc.)", max_length=255, null=True)),
                ('submit_location_to_infrastructure_distance', models.FloatField(blank=True, help_text='Distance in meters from the submit location to the infrastructure location.', null=True)),
                ('submit_location_to_infrastructure_direction_degrees', models.FloatField(blank=True, help_text='Direction from the submit location to the infrastructure location in degrees (0-360, where 0/360 is north, 90 is east, 180 is south, and 270 is west).', null=True)),
                ('submit_location_to_infrastructure_direction_cardinal', models.CharField(blank=True, choices=[('N', 'N'), ('NE', 'Ne'), ('E', 'E'), ('SE', 'Se'), ('S', 'S'), ('SW', 'Sw'), ('W', 'W'), ('NW', 'Nw')], help_text="Cardinal direction from the submit location to the infrastructure location (e.g., 'N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW').", max_length=255, null=True)),
                ('submit_location_to_infrastructure_direction_description', models.CharField(blank=True, help_text='Free text description of the direction from the submit location to the infrastructure location', max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('state_province', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='location',
            old_name='infrastructure_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='infrastructure_longitude',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='infrastructure_location_description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='infrastructure_location_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='submit_location_description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='submit_location_latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='submit_location_longitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='submit_location_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='submit_location_to_infrastructure_direction_cardinal',
        ),
        migrations.RemoveField(
            model_name='location',
            name='submit_location_to_infrastructure_direction_degrees',
        ),
        migrations.RemoveField(
            model_name='location',
            name='submit_location_to_infrastructure_direction_description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='submit_location_to_infrastructure_distance',
        ),
        migrations.AddField(
            model_name='crisis',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location'),
        ),
        migrations.AddField(
            model_name='crisis',
            name='nature_of_crisis',
            field=models.CharField(blank=True, help_text='e.g., earthquake, flood, hurricane, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crisis',
            name='nature_of_crisis_category',
            field=models.CharField(blank=True, choices=[('Natural Hazards', 'Natural Hazards'), ('Technological/Industrial Hazards', 'Technological Industral Hazards'), ('Human-Made Crisis', 'Humanmade Crisis')], help_text='e.g., natural disaster, human-made crisis, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crisisquestionanswer',
            name='impact_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.impactreport'),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, help_text='Free text description of the location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, help_text="Name of the location (e.g., 'Main Street Bridge', 'Downtown Intersection', etc.)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='impactreport',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.infrastructurelocation'),
        ),
    ]
