# Generated by Django 5.2.14 on 2026-06-17 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question2',
            name='distance_threshold_in_km',
        ),
        migrations.RemoveField(
            model_name='question2',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='question2',
            name='impact_report',
        ),
        migrations.RemoveField(
            model_name='question2',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='question2',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='question2',
            name='start_time',
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance_threshold_in_km', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('impact_report', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.impactreport')),
            ],
        ),
    ]
