# Generated by Django 5.2.14 on 2026-06-17 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_question2_distance_threshold_in_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question2',
            name='question_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.questiongroup'),
        ),
    ]
