# Generated by Django 5.2.14 on 2026-06-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question2_question_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciruser',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
