# Generated by Django 5.2.14 on 2026-06-18 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ciruser_pseudonym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactreport',
            name='accessibility',
        ),
        migrations.RemoveField(
            model_name='impactreport',
            name='crisis',
        ),
        migrations.RemoveField(
            model_name='impactreport',
            name='debris_description',
        ),
        migrations.RemoveField(
            model_name='impactreport',
            name='immediate_action',
        ),
        migrations.RemoveField(
            model_name='impactreport',
            name='immediate_action_reason',
        ),
        migrations.RemoveField(
            model_name='impactreport',
            name='is_critical_infrastructure',
        ),
        migrations.RemoveField(
            model_name='impactreport',
            name='nature_of_crisis',
        ),
        migrations.RemoveField(
            model_name='impactreport',
            name='nature_of_crisis_category',
        ),
    ]
