version: "3.8"

services:
  cir-frontend:
    build: .
    container_name: cir_frontend
    volumes:
      - .:/cir-frontend
      - /cir-frontend/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
